CREATE DATABASE BFA;

USE BFA;

CREATE TABLE Regions (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    [Name] NVARCHAR(200) NOT NULL,
    [Description] NVARCHAR(4000) NOT NULL,
    Departament NVARCHAR(100) NULL
);